### ISSUE TITLE
Utilisation de vos recherches

### ISSUE THREAD

**Issue by CyrilCharlier** [k20human/domoticz-atome#1]
Bonjour,

Je viens de tomber dans la domotique (mais sous Jeedom) et j'ai également la clé ATOME.

D'après votre licence MIT, je peux réutiliser, modifier, ... et tout ce qui va bien avec, votre code (en vous citant bien sûr).

Je préfère passer quand même par un écrit :) pour vous prévenir et voir si vous êtes toujours d'accord sur cette licence (et disponible en cas de questions ?).

N'étant pas très à l'aise en python, je vais le refondre en PHP avec les API de Jeedom.

bonne journée

**Comment by k20human** [comment]
Bonjour,

Aucun problème pour réutiliser mon code bien entendu. Je suis preneur pour le code bien entendu :)

Par contre pour info l'API de l'ATOME a changé depuis la nouvelle version, et je n'ai pas pris le temps de faire du reverse engineering donc le code de ce répo ne fonctionne plus ...

**Comment by CyrilCharlier** [comment]
Aucun souci : Mon futur git https://github.com/CyrilCharlier/Jeedom_CC_DirectE

Merci :)

**Comment by Phiphi69** [comment]
Bonjour,

j'aimerais traiter mes données de puissance instantanées ATOME en les recopiant sur un db locale. Je développe des algos de stats et d'optimisation.
L'API a été mise à jour et il faudrait donc mettre à jour votre code. Je n'y suis pas arrivé. Pensez-vous travailler dessus prochainement ? Si vous m'aiguillez, je pourrais peut-être le faire.

**Comment by k20human** [comment]
Bonjour,

Malheureusement depuis que j'ai reçu mon nouvel ATOME impossible de le faire fonctionner et je n'ai toujours pas pris le temps de contacter Direct Energie pour corriger le problème ...

De plus, l'API a en effet été mis à jour et il faudrait donc faire du reverse engineering pour trouver les bonnes routes ou contacter la société qui a édité la solution (j'étais en contact avec eux mais n'ai jamais eu de nouvelles).

Pour le moment donc c'est au point mort tant que je n'ai pas réglé ces 2 problèmes

**Comment by Phiphi69** [comment]
Merci pour votre retour.

Le 5 sept. 2018 09:52, "Kévin Mathieu" <notifications@github.com> a écrit :

Bonjour,

Malheureusement depuis que j'ai reçu mon nouvel ATOME impossible de le
faire fonctionner et je n'ai toujours pas pris le temps de contacter Direct
Energie pour corriger le problème ...

De plus, l'API a en effet été mis à jour et il faudrait donc faire du
reverse engineering pour trouver les bonnes routes ou contacter la société
qui a édité la solution (j'étais en contact avec eux mais n'ai jamais eu de
nouvelles).

Pour le moment donc c'est au point mort tant que je n'ai pas réglé ces 2
problèmes

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/k20human/domoticz-atome/issues/1#issuecomment-418634406>,
or mute the thread

**Comment by k20human** [comment]
Bonne nouvelle !
J'ai réussi à refaire fonctionner mon Atome et je me suis penché sur la nouvelle API.
J'ai réussi à m'en servir pour mettre à jour le script. ça tourne correctement depuis 2j chez moi.

Il n'est plus possible d'avoir les données par demi heure donc il faut modifier la crontab pour faire tourner le script toutes les fin d'heure (voir le README)

Je clos ce ticket

**Comment by CyrilCharlier** [comment]
Bonne nouvelle effectivement.
Dis voir, je n'ai qu'un compte Direct Energie, je n'ai pas de compte "atom" pure. Comment tu obtiens ton compte atome?

**Comment by k20human** [comment]
Depuis janvier le compte pour l'application Atome est le même que le compte Direct Energie

**Comment by CyrilCharlier** [comment]
au taff, le requête post est en 'failed' pour cause de login mais je suis derriere un proxy, je verrais bien chez moi ce soir.

**Comment by CyrilCharlier** [comment]
chelou, cela ne passe pas non plus. Après plus de 30 min à tout essayer je vais arrêter

![image](https://user-images.githubusercontent.com/11455745/45930023-0c5a3380-bf5a-11e8-87ec-127ea869faab.png)

![image](https://user-images.githubusercontent.com/11455745/45930029-2ac02f00-bf5a-11e8-8bae-7d5c55f0b5d2.png)

**Comment by k20human** [comment]
Et avec l'email à la place de l'ID ?
De plus il faut envoyer les données en JSON

**Comment by CyrilCharlier** [comment]
je vais retester mais j'avais commencé par du json (option raw dans Postman) et avec l'email et l'id.

mais il ce peut qu'à force de faire/défaire j'ai loupé un truc.  je vais retenter ce soir

merci :)
