### ISSUE TITLE
Avoid capcha

### ISSUE THREAD

**Issue by XciD** [k20human/domoticz-atome#4]
Hello, 

J'ai trouvé un contournement pour le login:

https://gist.github.com/XciD/cdb02ed7725a3a64cca126ffdd04d0ed

Si tu as besoin d'infos hésite pas

**Comment by k20human** [comment]
Merci mais je n'utilise plus ce plugin. Mon atome est beaucoup trop instable ...
A la place je récupère les informations directement sur mon compte Enedis via ce plugin : https://github.com/guillaumezin/DomoticzLinky

Si le coeur t'en dis tu peux faire une PR je la mergerai
